import type { Lang } from "./types";

export const en = {
  brand: "ORVIA",
  product: "Desk",
  demo: "DLM CASH LABS PRIVATE LIMITED",
  tape: { live: "Live" },
  nav: {
    market: "P2P",
    express: "Express",
    orders: "Orders",
    wallet: "Wallet",
    post: "Post ad",
    passes: "Passes",
    payments: "Payments",
    identity: "Identity",
    admin: "Admin",
    guide: "Guide",
    profile: "Profile",
    more: "More",
  },
  theme: { day: "Day", night: "Night", dark: "Dark", label: "Appearance" },
  lang: { label: "Language", en: "English", hi: "Hindi", ur: "Urdu" },
  role: { buyer: "Buyer", seller: "Merchant", admin: "Admin", suspended: "Suspended" },
  side: { buy: "Buy", sell: "Sell" },
  mode: { percent: "Percent", fixed: "Fixed", both: "Both", automatic: "Automatic", manual: "Manual" },
  common: {
    all: "All",
    online: "Online",
    amount: "Amount",
    price: "Price",
    available: "Available",
    limits: "Limits",
    payment: "Payment",
    status: "Status",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    close: "Close",
    back: "Back",
    submit: "Submit",
    approve: "Approve",
    reject: "Reject",
    revoke: "Revoke",
    pending: "Pending",
    active: "Active",
    copy: "Copy",
    copied: "Copied",
    none: "Nothing here yet",
    you: "You",
    fee: "Fee",
    total: "Total",
    receive: "You receive",
    pay: "You pay",
    details: "Details",
    user: "Person",
    note: "Note",
    balance: "Balance",
    actions: "Actions",
    view: "Open",
    trades: "trades",
    completion: "completion",
    justNow: "Just now",
    minutes: "{n} min",
    hours: "{n} h",
    days: "{n} d",
    coin: "Coin",
    fiat: "Fiat",
    country: "Country",
    name: "Full name",
    merchant: "Merchant",
    terms: "Terms",
    search: "Search merchant",
    window: "Pay window",
    locked: "Locked",
    free: "Free",
    count: "{n} ads",
  },
  status: {
    created: "Awaiting payment",
    paid: "Paid, release coin",
    released: "Completed",
    cancelled: "Cancelled",
    disputed: "In dispute",
    pending_admin: "Waiting for admin",
    auto_sent: "Sent automatically",
    sent: "Sent by admin",
    rejected: "Rejected",
    suspended: "Suspended",
    revoked: "Revoked",
    approved: "Approved",
  },
  system: {
    created: "Order opened. Pay off the desk, then mark paid.",
    paid: "Buyer marked the fiat as paid.",
    released: "Coin released.",
    cancelled: "Order cancelled. Coin returned.",
    disputed: "Dispute opened. Admin can decide.",
  },
  market: {
    sub: "Buy and sell practice coins with merchants. Fiat moves off this desk. Coin moves here only after release.",
    amountPh: "Fiat amount",
    empty: "No ad matches these filters.",
    yourAd: "Your ad",
    verify: "Verify",
    waiting: "In review",
    verified: "Licensed",
    onlineOnly: "Online only",
    followingOnly: "Following",
    float: "Floating price",
    minComp: "Needs {n}% completion",
    extraId: "Identity required",
  },
  trade: {
    titleBuy: "Buy coin",
    titleSell: "Sell coin",
    youPay: "You pay off the desk",
    youReceive: "You receive",
    buyerFee: "Buyer fee",
    sellerFee: "Seller fee",
    escrowNote: "Both fees settle in coin. The buyer fee is taken from the coin you receive. The seller fee is taken from the seller.",
    needPass: "A pass from {name} is required before the first buy. After approval you do not verify again, unless they revoke it.",
    kycTitle: "Identity for this merchant",
    confirm: "Open order",
    offDesk: "Fiat never sits on this desk.",
    chatEmpty: "No messages yet.",
    chatPh: "Write a message",
    send: "Send",
    markPaid: "I have paid",
    release: "Release coin",
    cancel: "Cancel order",
    dispute: "Open dispute",
    windowLeft: "Pay window",
    windowOver: "Pay window has passed. You can still mark paid.",
    private: "This order is not yours.",
    missing: "Order not found.",
    adminRelease: "Admin release",
    adminCancel: "Admin cancel",
    min: "Minimum",
    max: "Maximum",
    net: "After buyer fee",
    room: "Order room",
    rate: "Rate the counterparty",
    rated: "Your rating",
    block: "Block",
    unblock: "Unblock",
    follow: "Follow",
    unfollow: "Unfollow",
    appealWhy: "Reason",
    appeal: {
      not_released: "Coin was not released",
      wrong_name: "Name does not match",
      no_reply: "No reply",
      amount: "Amount is wrong",
    },
  },
  ads: {
    title: "Post an ad",
    sub: "Only a merchant with an active license can post. Selling locks coin from the wallet into the ad.",
    side: "Your side",
    price: "Price per coin",
    min: "Minimum coin",
    max: "Maximum coin",
    inventory: "Coin to offer or seek",
    rails: "Payment rails",
    termsPh: "Optional terms",
    defaultTerms: "Pay only the account shown in the order room. Mark paid only after the fiat leaves your account. Coin is released after that.",
    needLicense: "An active merchant license is required. Finish identity and wait for admin.",
    my: "Your ads",
    pause: "Pause",
    resume: "Resume",
    close: "Close ad",
    empty: "You have no ads.",
    posted: "Ad is live.",
    saved: "Ad updated.",
    busy: "Close the open orders on this ad first.",
    mode: "Price type",
    fixed: "Fixed",
    float: "Floating",
    margin: "Margin percent",
    window: "Payment window",
    auto: "Auto reply",
    autoPh: "Sent when an order opens",
    needId: "Require identity",
    minComp: "Minimum completion",
    break: "Take a break",
    edit: "Edit",
    railsCap: "Up to five rails",
  },
  orders: {
    title: "Orders",
    empty: "No orders for this seat yet.",
    missing: "Order not found.",
    private: "This order belongs to another seat.",
    counterparty: "Counterparty",
    room: "Order room",
    youBuy: "You buy",
    youSell: "You sell",
  },
  wallet: {
    title: "Wallet",
    sub: "Practice balances only. A transfer to another desk is completed by admin, unless the amount is under the limit and admin set it to automatic.",
    free: "Free",
    inAds: "In ads",
    inOrders: "In orders",
    pendingOut: "Waiting to send",
    ref: "Reference value",
    topup: "Practice top-up",
    topupNote: "Adds 100 practice coins. Nothing arrives from outside.",
    topupGo: "Add 100",
    withdraw: "Send out",
    address: "Destination address",
    addressPh: "Address on the other desk",
    network: "Path",
    amount: "Coin amount",
    limitIs: "Admin limit: {n} coins",
    previewAuto: "This request will be marked sent at once.",
    previewManual: "This request will wait until admin sends it.",
    history: "Transfers",
    empty: "No transfers yet.",
    policy: "How sending works",
  },
  kyc: {
    title: "Identity",
    sellerSub: "A merchant license comes from admin. Choose a national identity, a passport, or the tax number used in your country. Only the last four digits are kept.",
    buyerSub: "The merchant reviews this once. If they approve, you receive a pass: their four digits, then four random digits. You will not verify with them again unless they revoke the pass.",
    doc: "Document",
    last4: "Last four digits",
    last4Hint: "Exactly four digits. The rest of the number is never stored.",
    declare: "I confirm these four digits match my document, and I understand the full number is not stored.",
    tax: "Tax number type",
    submitSeller: "Ask admin for a merchant license",
    submitBuyer: "Send to merchant",
    pendingAdmin: "Waiting for admin.",
    pendingSeller: "Waiting for the merchant.",
    approved: "Approved.",
    rejected: "Rejected. You can send it again.",
    none: "No request yet.",
    forMerchant: "For {name}",
    held: "Current merchant license",
    front: "Front of the document",
    back: "Back of the document",
    selfie: "Face check",
    attach: "Mark attached",
    attached: "Attached",
    missing: "Not attached",
    docsNote: "This practice desk records only that a file was marked. No image is stored.",
    levelNone: "Not verified",
    levelPending: "In review",
    levelMerchant: "Merchant verified",
    levelRejected: "Needs a new check",
    why: "Reason",
    evidence: "Evidence",
    reasons: {
      incomplete: "Documents incomplete",
      blur: "Document unreadable",
      mismatch: "Name does not match the digits",
      expired: "Document is out of date",
    },
  },
  pass: {
    title: "Passes",
    sub: "A buyer pass is permanent with that merchant until they revoke it. Revoke means a new identity check. The merchant can approve a new request at any time.",
    merchantLicense: "Merchant license",
    noneLicense: "No merchant license on this seat.",
    code: "Code",
    yourPasses: "Passes you hold",
    issued: "Requests and passes you decide",
    emptyHeld: "You hold no pass yet. Verify from a merchant ad.",
    emptyIssued: "No buyer has asked you yet.",
    permanent: "Permanent with this merchant while active.",
    revokedNote: "Revoked. A new identity check is required before you can buy from them again.",
    by: "Merchant",
    grant: "Grant pass",
    deny: "Deny",
    holder: "Buyer",
    suspended: "License suspended by admin.",
  },
  admin: {
    title: "Admin desk",
    gate: "Switch to the admin seat to manage fees, identity, and outgoing transfers.",
    switch: "Sit as admin",
    overview: "Overview",
    fees: "Fees",
    withdrawals: "Transfers",
    identity: "Identity",
    coins: "Coins",
    orders: "Orders",
    users: "People",
    policy: "Buyer and seller fees are separate. Use a percent, a fixed coin amount on each trade, or both together.",
    buyerPercent: "Buyer percent",
    sellerPercent: "Seller percent",
    buyerFixed: "Buyer fixed coin",
    sellerFixed: "Seller fixed coin",
    under: "Under the limit",
    over: "At the limit and above",
    threshold: "Limit in coin",
    save: "Save rules",
    saved: "Rules saved.",
    queueEmpty: "Queue is clear.",
    send: "Mark sent",
    reject: "Return coin",
    listed: "Listed",
    unlist: "Hide",
    list: "List",
    addCoin: "Issue a random coin",
    added: "Coin {coin} is listed.",
    newCoin: "New coin",
    suspend: "Suspend license",
    resume: "Restore license",
    openOrders: "Open orders",
    pendingKyc: "Identity waiting",
    pendingWd: "Transfers waiting",
    treasury: "Fees collected",
    noTreasury: "No fees yet.",
    merchantDecides: "The merchant decides buyer passes. This list is only for oversight.",
    sellerQueue: "Merchant license requests",
    people: "Seats",
    sendBody: "Outgoing coin to another desk is sent from this queue, except amounts under the limit when automatic is on.",
    noLicense: "No license",
    controls: "Controls",
    coinForm: "List a coin",
    symbol: "Symbol",
    coinName: "Name",
    refPrice: "Reference price",
    minOut: "Minimum send",
    deposits: "Practice deposits",
    withdrawalsOn: "Outgoing sends",
    on: "On",
    off: "Off",
    saveCoin: "Save coin",
    coinSaved: "Coin {coin} updated.",
    desk: "Desk",
    deskOpen: "Desk is open. New ads and orders are allowed.",
    deskClosed: "Desk is closed. No new ads or orders.",
    openDesk: "Open desk",
    closeDesk: "Close desk",
    holdOut: "Hold sends",
    releaseOut: "Allow sends",
    freeze: "Freeze seat",
    unfreeze: "Unfreeze seat",
    frozen: "Seat frozen. They cannot trade or send.",
    auditTitle: "Control log",
    auditEmpty: "No control has been used yet.",
    auditKycYes: "Approved merchant check · {detail}",
    auditKycNo: "Rejected merchant check · {detail}",
    auditCoin: "Coin change · {detail}",
    auditSeat: "Seat control · {detail}",
    auditDesk: "Desk · {detail}",
    auditRelease: "Forced release · {detail}",
    auditCancel: "Forced cancel · {detail}",
    auditSend: "Marked transfer sent · {detail}",
    auditReturn: "Returned transfer · {detail}",
    seats: "Seat controls",
  },
  pay: {
    title: "Payment methods",
    sub: "Shown inside an order so the buyer knows where fiat should go. Never a real collection account in this practice desk.",
    add: "Save method",
    rail: "Rail",
    label: "Name",
    details: "Destination",
    detailsPh: "Number or handle",
    saved: "Saved methods",
    remove: "Remove",
    empty: "No method saved.",
    need: "Save a payment method before you post.",
  },
  express: {
    title: "Express",
    sub: "Type a fiat amount or a coin amount. The desk picks the best price, can skip ads that ask for extra identity, and opens the same order.",
    youGet: "Coin you get",
    best: "Best merchant",
    none: "No licensed ad matches.",
    go: "Continue",
    pay: "Fiat you pay",
    unitFiat: "Fiat amount",
    unitCoin: "Coin amount",
    skipId: "Skip ads that require extra identity",
    fee: "Fee",
    window: "Pay window",
    buySide: "Buy",
    sellSide: "Sell",
  },
  help: {
    title: "How this desk works",
    aT: "Two seats, one coin",
    aB: "A merchant posts an ad. A buyer takes it. Fiat is paid outside ORVIA. Coin stays locked until the merchant releases it.",
    bT: "Merchant license",
    bB: "Admin issues a merchant license after identity. Documents are a national identity, a passport, or the tax number of the country, such as PAN in India. Only the last four digits are stored.",
    cT: "Buyer pass",
    cB: "The first buy from a merchant needs identity with that merchant. They may grant a pass made of their four digits plus four random digits. Later buys skip identity. If they revoke the pass, identity is required again. They may approve a new request whenever they want.",
    dT: "Fees",
    dB: "Admin sets a buyer fee and a seller fee. Each can be a percent, a fixed amount of coin per trade, or both at once.",
    eT: "Sending coin out",
    eB: "A transfer to an address on another desk is completed by admin. If the amount is under the limit, admin can choose automatic or manual. The limit starts at five coins and can be changed.",
    fT: "What stays on the desk",
    fB: "Balances, orders, and licenses stay with this desk. Nothing is broadcast from here, and identity keeps only the last four digits.",
  },
  profile: {
    title: "Profile",
    acting: "You are acting as",
    switch: "Switch seat",
    seat: "Roles on this desk stay in this browser. Merchants grant passes and release coin. Admin sets fees and transfers. Admin is not self-serve.",
    reset: "Restore desk data",
    resetWarn: "This restores the original ads, orders, and licenses.",
    resetDo: "Reset now",
    done: "Desk restored.",
    blocked: "Blocked",
    following: "Following",
    noneList: "None yet.",
  },
  footer: { sim: "DLM CASH LABS PRIVATE LIMITED", rights: "ORVIA" },
  rail: {
    upi: "UPI",
    imps: "IMPS",
    bank: "Bank transfer",
    paytm: "Paytm",
    jazz: "JazzCash",
    easy: "Easypaisa",
    card: "Card",
  },
  fiatName: { INR: "Indian rupee", USD: "US dollar", PKR: "Pakistani rupee", AED: "UAE dirham", EUR: "Euro" },
  coinName: {
    ORB: "Orbit",
    VLT: "Vault",
    KYN: "Kyne",
    AUR: "Aura",
    PXN: "Pexon",
    LUM: "Lumen",
    NRX: "Nerix",
    HAL: "Halo",
    BTC: "Bitcoin",
    ETH: "Ethereum",
    USDT: "Tether",
    BNB: "BNB",
    XRP: "XRP",
    USDC: "USD Coin",
    SOL: "Solana",
    TRX: "Tron",
    ZEC: "Zcash",
    HYPE: "Hyperliquid",
  },
  country: {
    IN: "India",
    US: "United States",
    GB: "United Kingdom",
    PK: "Pakistan",
    AE: "United Arab Emirates",
    CA: "Canada",
    AU: "Australia",
    DE: "Germany",
    FR: "France",
    BR: "Brazil",
    NG: "Nigeria",
    ZA: "South Africa",
    SG: "Singapore",
    BD: "Bangladesh",
    NP: "Nepal",
    LK: "Sri Lanka",
    CN: "China",
    JP: "Japan",
    ID: "Indonesia",
    PH: "Philippines",
    KE: "Kenya",
    SA: "Saudi Arabia",
    TR: "Turkey",
    MX: "Mexico",
    ES: "Spain",
    IT: "Italy",
    NL: "Netherlands",
    QA: "Qatar",
  },
  tax: {
    PAN: "Permanent account number",
    SSN: "Social security number",
    ITIN: "Individual taxpayer number",
    UTR: "Unique taxpayer reference",
    NINO: "National insurance number",
    NTN: "National tax number",
    TRN: "Tax registration number",
    SIN: "Social insurance number",
    TFN: "Tax file number",
    STEUER: "Tax identification number",
    SPI: "Tax number",
    CF: "Fiscal code",
    NIF: "Tax identification number",
    BSN: "Citizen service number",
    CPF: "Natural persons register",
    RFC: "Federal taxpayer registry",
    TIN_NG: "Taxpayer identification number",
    SARS: "Revenue service number",
    NRIC: "National registration identity",
    TIN_BD: "Taxpayer identification number",
    PAN_NP: "Permanent account number",
    TIN_LK: "Taxpayer identification number",
    TIN_CN: "Taxpayer identification number",
    MYNO: "Individual number",
    NPWP: "Taxpayer registration number",
    TIN_PH: "Taxpayer identification number",
    KRA: "Revenue authority number",
    TIN_SA: "Taxpayer identification number",
    VKN: "Tax identity number",
    TIN_QA: "Tax card number",
  },
  doc: { national_id: "National identity", passport: "Passport", tax_id: "Tax number" },
  net: { mesh: "Orvia mesh", north: "North path", south: "South path" },
  err: {
    own: "You cannot take your own ad.",
    license: "You need an active pass from this merchant.",
    merchant: "Selling needs an active merchant license.",
    limits: "Amount is outside the ad limits.",
    available: "Not enough coin left on this ad.",
    balance: "Not enough free coin.",
    fee: "Fees would consume the whole trade. Raise the amount or lower the fees.",
    address: "Enter a destination of at least 8 characters.",
    amount: "Enter a valid amount.",
    rails: "Choose at least one payment rail.",
    price: "Enter a valid price.",
    inventory: "Enter how much coin the ad should hold.",
    range: "Minimum cannot exceed maximum.",
    name: "Enter the full name.",
    last4: "Enter exactly four digits.",
    pending: "A review is already open.",
    pass: "A pass is already active.",
    forbidden: "This seat cannot do that.",
    busy: "Open orders still use this ad.",
    declare: "Confirm the four digits first.",
    country: "Choose a country.",
    tax: "Choose the tax number type.",
    closed: "This order is already finished.",
    payment: "Choose a payment rail.",
    docs: "Attach the front, the back when required, and the face check.",
    symbol: "Use 3 to 5 letters for the symbol.",
    duplicate: "That symbol already exists.",
    frozen: "This seat is frozen.",
    desk: "The desk is closed for new trades.",
    coinOff: "This coin cannot move that way right now.",
    minOut: "Amount is under this coin's minimum send.",
    self: "The admin seat cannot be frozen.",
    why: "Choose a reason before you reject.",
    blocked: "One of you has blocked the other.",
    kyc: "This ad requires identity first.",
    completion: "Your completion is below this ad.",
  },
};

export type Copy = typeof en;

export const hi = {
  brand: "ORVIA",
  product: "पटल",
  demo: "डीएलएम कैश लैब्स प्राइवेट लिमिटेड",
  tape: { live: "लाइव" },
  nav: {
    market: "बाज़ार",
    express: "त्वरित",
    orders: "सौदे",
    wallet: "बटुआ",
    post: "विज्ञापन",
    passes: "अनुज्ञप्ति",
    payments: "भुगतान",
    identity: "पहचान",
    admin: "प्रशासन",
    guide: "मार्गदर्शिका",
    profile: "खाता",
    more: "और",
  },
  theme: { day: "दिन", night: "रात", dark: "गहरा", label: "रूप" },
  lang: { label: "भाषा", en: "अंग्रेज़ी", hi: "हिन्दी", ur: "उर्दू" },
  role: { buyer: "खरीदार", seller: "व्यापारी", admin: "प्रशासन", suspended: "रोकी गई" },
  side: { buy: "खरीदें", sell: "बेचें" },
  mode: { percent: "प्रतिशत", fixed: "निश्चित", both: "दोनों", automatic: "स्वचालित", manual: "मानवी" },
  common: {
    all: "सभी",
    online: "उपस्थित",
    amount: "राशि",
    price: "मूल्य",
    available: "उपलब्ध",
    limits: "सीमा",
    payment: "भुगतान",
    status: "स्थिति",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सहेजें",
    close: "बंद करें",
    back: "वापस",
    submit: "जमा करें",
    approve: "स्वीकार करें",
    reject: "अस्वीकार करें",
    revoke: "वापस लें",
    pending: "प्रतीक्षा",
    active: "सक्रिय",
    copy: "प्रतिलिपि",
    copied: "प्रतिलिपि बन गई",
    none: "अभी यहाँ कुछ नहीं",
    you: "आप",
    fee: "शुल्क",
    total: "योग",
    receive: "आपको मिलेगा",
    pay: "आप देंगे",
    details: "विवरण",
    user: "व्यक्ति",
    note: "टिप्पणी",
    balance: "शेष",
    actions: "कार्य",
    view: "खोलें",
    trades: "सौदे",
    completion: "पूर्णता",
    justNow: "अभी",
    minutes: "{n} मिनट",
    hours: "{n} घंटे",
    days: "{n} दिन",
    coin: "सिक्का",
    fiat: "मुद्रा",
    country: "देश",
    name: "पूरा नाम",
    merchant: "व्यापारी",
    terms: "शर्तें",
    search: "व्यापारी खोजें",
    window: "भुगतान अवधि",
    locked: "अवरुद्ध",
    free: "मुक्त",
    count: "{n} विज्ञापन",
  },
  status: {
    created: "भुगतान की प्रतीक्षा",
    paid: "भुगतान हुआ, सिक्का छोड़ें",
    released: "पूर्ण",
    cancelled: "रद्द",
    disputed: "विवाद में",
    pending_admin: "प्रशासन की प्रतीक्षा",
    auto_sent: "स्वतः भेज दिया गया",
    sent: "प्रशासन ने भेजा",
    rejected: "अस्वीकृत",
    suspended: "रोकी गई",
    revoked: "वापस ली गई",
    approved: "स्वीकृत",
  },
  system: {
    created: "सौदा खुला। पटल के बाहर भुगतान करें, फिर भुगतान चिह्नित करें।",
    paid: "खरीदार ने मुद्रा भुगतान चिह्नित किया।",
    released: "सिक्का छोड़ दिया गया।",
    cancelled: "सौदा रद्द। सिक्का लौटा।",
    disputed: "विवाद खुला। प्रशासन निर्णय कर सकता है।",
  },
  market: {
    sub: "व्यापारियों के साथ अभ्यास सिक्के खरीदें और बेचें। मुद्रा इस पटल के बाहर जाती है। सिक्का यहीं तभी हिलता है जब व्यापारी उसे छोड़े।",
    amountPh: "मुद्रा राशि",
    empty: "इन छन्नी से कोई विज्ञापन नहीं मिला।",
    yourAd: "आपका विज्ञापन",
    verify: "पहचान करें",
    waiting: "समीक्षा में",
    verified: "अनुज्ञप्त",
    onlineOnly: "केवल उपस्थित",
    followingOnly: "अनुसरण",
    float: "चल मूल्य",
    minComp: "{n}% पूर्णता चाहिए",
    extraId: "पहचान आवश्यक",
  },
  trade: {
    titleBuy: "सिक्का खरीदें",
    titleSell: "सिक्का बेचें",
    youPay: "पटल के बाहर आप देंगे",
    youReceive: "आपको मिलेगा",
    buyerFee: "खरीदार शुल्क",
    sellerFee: "विक्रेता शुल्क",
    escrowNote: "दोनों शुल्क सिक्के में कटते हैं। खरीदार शुल्क मिलने वाले सिक्के से कटता है। विक्रेता शुल्क विक्रेता से कटता है।",
    needPass: "{name} से पहली खरीद से पहले अनुज्ञप्ति चाहिए। स्वीकृति के बाद फिर पहचान नहीं, जब तक वे उसे वापस न लें।",
    kycTitle: "इस व्यापारी के लिए पहचान",
    confirm: "सौदा खोलें",
    offDesk: "मुद्रा इस पटल पर नहीं ठहरती।",
    chatEmpty: "अभी कोई संदेश नहीं।",
    chatPh: "संदेश लिखें",
    send: "भेजें",
    markPaid: "मैंने भुगतान किया",
    release: "सिक्का छोड़ें",
    cancel: "सौदा रद्द करें",
    dispute: "विवाद खोलें",
    windowLeft: "भुगतान अवधि",
    windowOver: "भुगतान अवधि बीत गई। फिर भी भुगतान चिह्नित कर सकते हैं।",
    private: "यह सौदा आपका नहीं है।",
    missing: "सौदा नहीं मिला।",
    adminRelease: "प्रशासन छोड़े",
    adminCancel: "प्रशासन रद्द करे",
    min: "न्यूनतम",
    max: "अधिकतम",
    net: "खरीदार शुल्क के बाद",
    room: "सौदा कक्ष",
    rate: "दूसरे पक्ष को आँकें",
    rated: "आपका आँक",
    block: "रोकें",
    unblock: "रोक हटाएँ",
    follow: "अनुसरण करें",
    unfollow: "अनुसरण हटाएँ",
    appealWhy: "कारण",
    appeal: {
      not_released: "सिक्का नहीं छोड़ा गया",
      wrong_name: "नाम मेल नहीं खाता",
      no_reply: "कोई उत्तर नहीं",
      amount: "राशि गलत है",
    },
  },
  ads: {
    title: "विज्ञापन दें",
    sub: "केवल सक्रिय अनुज्ञप्ति वाला व्यापारी विज्ञापन दे सकता है। बेचने पर बटुए का सिक्का विज्ञापन में अवरुद्ध होता है।",
    side: "आपका पक्ष",
    price: "प्रति सिक्का मूल्य",
    min: "न्यूनतम सिक्का",
    max: "अधिकतम सिक्का",
    inventory: "जितना सिक्का देना या माँगना है",
    rails: "भुगतान मार्ग",
    termsPh: "वैकल्पिक शर्तें",
    defaultTerms: "केवल सौदा कक्ष में दिखाया खाता भरें। मुद्रा निकलने के बाद ही भुगतान चिह्नित करें। उसके बाद सिक्का छोड़ा जाता है।",
    needLicense: "सक्रिय व्यापारी अनुज्ञप्ति चाहिए। पहचान पूरी करें और प्रशासन की प्रतीक्षा करें।",
    my: "आपके विज्ञापन",
    pause: "रोकें",
    resume: "जारी करें",
    close: "विज्ञापन बंद करें",
    empty: "आपका कोई विज्ञापन नहीं।",
    posted: "विज्ञापन चल रहा है।",
    saved: "विज्ञापन अद्यतन।",
    busy: "पहले इस विज्ञापन के खुले सौदे बंद करें।",
    mode: "मूल्य का प्रकार",
    fixed: "निश्चित",
    float: "चल",
    margin: "हाशिया प्रतिशत",
    window: "भुगतान अवधि",
    auto: "स्वतः उत्तर",
    autoPh: "सौदा खुलते ही भेजा जाता है",
    needId: "पहचान आवश्यक",
    minComp: "न्यूनतम पूर्णता",
    break: "विराम लें",
    edit: "संपादित करें",
    railsCap: "अधिकतम पाँच मार्ग",
  },
  orders: {
    title: "सौदे",
    empty: "इस भूमिका में अभी कोई सौदा नहीं।",
    missing: "सौदा नहीं मिला।",
    private: "यह सौदा दूसरी सीट का है।",
    counterparty: "दूसरा पक्ष",
    room: "सौदा कक्ष",
    youBuy: "आप खरीद रहे हैं",
    youSell: "आप बेच रहे हैं",
  },
  wallet: {
    title: "बटुआ",
    sub: "केवल अभ्यास शेष। दूसरे पटल के पते पर सिक्का प्रशासन भेजता है, सिवाय जब राशि सीमा से कम हो और प्रशासन ने उसे स्वचालित रखा हो।",
    free: "मुक्त",
    inAds: "विज्ञापन में",
    inOrders: "सौदों में",
    pendingOut: "भेजने की प्रतीक्षा",
    ref: "संदर्भ मूल्य",
    topup: "अभ्यास वृद्धि",
    topupNote: "१०० अभ्यास सिक्के जुड़ते हैं। बाहर से कुछ नहीं आता।",
    topupGo: "१०० जोड़ें",
    withdraw: "बाहर भेजें",
    address: "गंतव्य पता",
    addressPh: "दूसरे पटल का पता",
    network: "मार्ग",
    amount: "सिक्का राशि",
    limitIs: "प्रशासन सीमा: {n} सिक्के",
    previewAuto: "यह अनुरोध तुरंत भेजा हुआ चिह्नित होगा।",
    previewManual: "यह अनुरोध तब तक रुकेगा जब तक प्रशासन न भेजे।",
    history: "अंतरण",
    empty: "अभी कोई अंतरण नहीं।",
    policy: "भेजने का ढंग",
  },
  kyc: {
    title: "पहचान",
    sellerSub: "व्यापारी अनुज्ञप्ति प्रशासन देता है। राष्ट्रीय पहचान, पारपत्र, या अपने देश का कर क्रमांक चुनें। भारत में यह पैन होता है। केवल अंतिम चार अंक रखे जाते हैं।",
    buyerSub: "व्यापारी इसे एक बार देखता है। स्वीकार करने पर अनुज्ञप्ति मिलती है: उनके चार अंक, फिर चार यादृच्छिक अंक। वे वापस न लें तो उनसे फिर पहचान नहीं करनी।",
    doc: "दस्तावेज़",
    last4: "अंतिम चार अंक",
    last4Hint: "ठीक चार अंक। शेष क्रमांक कभी संचित नहीं होता।",
    declare: "मैं पुष्टि करता हूँ कि ये चार अंक मेरे दस्तावेज़ से मेल खाते हैं, और पूरा क्रमांक संचित नहीं होता।",
    tax: "कर क्रमांक का प्रकार",
    submitSeller: "प्रशासन से व्यापारी अनुज्ञप्ति माँगें",
    submitBuyer: "व्यापारी को भेजें",
    pendingAdmin: "प्रशासन की प्रतीक्षा।",
    pendingSeller: "व्यापारी की प्रतीक्षा।",
    approved: "स्वीकृत।",
    rejected: "अस्वीकृत। फिर भेज सकते हैं।",
    none: "अभी कोई अनुरोध नहीं।",
    forMerchant: "{name} के लिए",
    held: "वर्तमान व्यापारी अनुज्ञप्ति",
    front: "दस्तावेज़ का अग्र भाग",
    back: "दस्तावेज़ का पृष्ठ भाग",
    selfie: "चेहरे की जाँच",
    attach: "संलग्न चिह्नित करें",
    attached: "संलग्न",
    missing: "संलग्न नहीं",
    docsNote: "यह अभ्यास पटल केवल यह दर्ज करता है कि फ़ाइल चिह्नित हुई। कोई चित्र संचित नहीं होता।",
    levelNone: "सत्यापित नहीं",
    levelPending: "समीक्षा में",
    levelMerchant: "व्यापारी सत्यापित",
    levelRejected: "नई जाँच चाहिए",
    why: "कारण",
    evidence: "साक्ष्य",
    reasons: {
      incomplete: "दस्तावेज़ अधूरे",
      blur: "दस्तावेज़ पढ़ा नहीं जा सका",
      mismatch: "नाम अंकों से नहीं मिलता",
      expired: "दस्तावेज़ पुराना है",
    },
  },
  pass: {
    title: "अनुज्ञप्ति",
    sub: "खरीदार अनुज्ञप्ति उस व्यापारी के साथ तब तक स्थायी है जब तक वे उसे वापस न लें। वापसी का अर्थ नई पहचान है। नया अनुरोध वे कभी भी स्वीकार कर सकते हैं।",
    merchantLicense: "व्यापारी अनुज्ञप्ति",
    noneLicense: "इस भूमिका में व्यापारी अनुज्ञप्ति नहीं।",
    code: "संकेत",
    yourPasses: "आपके पास अनुज्ञप्तियाँ",
    issued: "आप जिन अनुरोधों पर निर्णय करते हैं",
    emptyHeld: "अभी कोई अनुज्ञप्ति नहीं। व्यापारी के विज्ञापन से पहचान करें।",
    emptyIssued: "अभी किसी खरीदार ने नहीं पूछा।",
    permanent: "सक्रिय रहते इस व्यापारी के साथ स्थायी।",
    revokedNote: "वापस ली गई। उनसे फिर खरीदने से पहले नई पहचान चाहिए।",
    by: "व्यापारी",
    grant: "अनुज्ञप्ति दें",
    deny: "अस्वीकार करें",
    holder: "खरीदार",
    suspended: "प्रशासन ने अनुज्ञप्ति रोक दी।",
  },
  admin: {
    title: "प्रशासन पटल",
    gate: "शुल्क, पहचान और बाहर जाने वाले अंतरण के लिए प्रशासन की भूमिका चुनें।",
    switch: "प्रशासन बनें",
    overview: "सार",
    fees: "शुल्क",
    withdrawals: "अंतरण",
    identity: "पहचान",
    coins: "सिक्के",
    orders: "सौदे",
    users: "लोग",
    policy: "खरीदार और विक्रेता का शुल्क अलग है। प्रतिशत, हर सौदे पर निश्चित सिक्का, या दोनों एक साथ रख सकते हैं।",
    buyerPercent: "खरीदार प्रतिशत",
    sellerPercent: "विक्रेता प्रतिशत",
    buyerFixed: "खरीदार निश्चित सिक्का",
    sellerFixed: "विक्रेता निश्चित सिक्का",
    under: "सीमा से कम",
    over: "सीमा पर और उससे अधिक",
    threshold: "सिक्के में सीमा",
    save: "नियम सहेजें",
    saved: "नियम सहेजे गए।",
    queueEmpty: "कतार खाली है।",
    send: "भेजा चिह्नित करें",
    reject: "सिक्का लौटाएँ",
    listed: "सूची में",
    unlist: "छिपाएँ",
    list: "दिखाएँ",
    addCoin: "यादृच्छिक सिक्का जारी करें",
    added: "सिक्का {coin} सूची में है।",
    newCoin: "नया सिक्का",
    suspend: "अनुज्ञप्ति रोकें",
    resume: "अनुज्ञप्ति लौटाएँ",
    openOrders: "खुले सौदे",
    pendingKyc: "पहचान प्रतीक्षा",
    pendingWd: "अंतरण प्रतीक्षा",
    treasury: "एकत्र शुल्क",
    noTreasury: "अभी शुल्क नहीं।",
    merchantDecides: "खरीदार अनुज्ञप्ति व्यापारी तय करता है। यह सूची केवल देखरेख के लिए है।",
    sellerQueue: "व्यापारी अनुज्ञप्ति के अनुरोध",
    people: "भूमिकाएँ",
    sendBody: "दूसरे पटल पर जाने वाला सिक्का इसी कतार से भेजा जाता है, सिवाय सीमा से कम राशि के जब स्वचालित चुना हो।",
    noLicense: "अनुज्ञप्ति नहीं",
    controls: "नियंत्रण",
    coinForm: "सिक्का सूची में रखें",
    symbol: "संकेत",
    coinName: "नाम",
    refPrice: "संदर्भ मूल्य",
    minOut: "न्यूनतम प्रेषण",
    deposits: "अभ्यास जमा",
    withdrawalsOn: "बाहर भेजना",
    on: "चालू",
    off: "बंद",
    saveCoin: "सिक्का सहेजें",
    coinSaved: "सिक्का {coin} अद्यतन हुआ।",
    desk: "पटल",
    deskOpen: "पटल खुला है। नए विज्ञापन और सौदे चलेंगे।",
    deskClosed: "पटल बंद है। नए विज्ञापन या सौदे नहीं।",
    openDesk: "पटल खोलें",
    closeDesk: "पटल बंद करें",
    holdOut: "प्रेषण रोकें",
    releaseOut: "प्रेषण चालू करें",
    freeze: "भूमिका रोकें",
    unfreeze: "भूमिका खोलें",
    frozen: "भूमिका रुकी। वे सौदा या प्रेषण नहीं कर सकते।",
    auditTitle: "नियंत्रण पत्र",
    auditEmpty: "अभी कोई नियंत्रण नहीं हुआ।",
    auditKycYes: "व्यापारी जाँच स्वीकृत · {detail}",
    auditKycNo: "व्यापारी जाँच अस्वीकृत · {detail}",
    auditCoin: "सिक्का परिवर्तन · {detail}",
    auditSeat: "भूमिका नियंत्रण · {detail}",
    auditDesk: "पटल · {detail}",
    auditRelease: "बलपूर्वक मुक्त · {detail}",
    auditCancel: "बलपूर्वक रद्द · {detail}",
    auditSend: "अंतरण भेजा चिह्नित · {detail}",
    auditReturn: "अंतरण लौटाया · {detail}",
    seats: "भूमिका नियंत्रण",
  },
  pay: {
    title: "भुगतान साधन",
    sub: "सौदा कक्ष में दिखाया जाता है ताकि खरीदार जाने मुद्रा कहाँ जानी है। इस अभ्यास पटल पर कोई वास्तविक संग्रह खाता नहीं।",
    add: "साधन सहेजें",
    rail: "मार्ग",
    label: "नाम",
    details: "गंतव्य",
    detailsPh: "क्रमांक या पता",
    saved: "सहेजे साधन",
    remove: "हटाएँ",
    empty: "कोई साधन नहीं।",
    need: "विज्ञापन से पहले एक भुगतान साधन सहेजें।",
  },
  express: {
    title: "त्वरित",
    sub: "मुद्रा की राशि या सिक्के की राशि लिखें। पटल सबसे अच्छा मूल्य चुनता है। अतिरिक्त पहचान वाले विज्ञापन छोड़े जा सकते हैं। सौदा वही खुलता है।",
    youGet: "जितना सिक्का मिलेगा",
    best: "सर्वोत्तम व्यापारी",
    none: "कोई अनुज्ञप्त विज्ञापन नहीं मिला।",
    go: "आगे बढ़ें",
    pay: "जितनी मुद्रा देंगे",
    unitFiat: "मुद्रा की राशि",
    unitCoin: "सिक्के की राशि",
    skipId: "अतिरिक्त पहचान वाले विज्ञापन छोड़ें",
    fee: "शुल्क",
    window: "भुगतान अवधि",
    buySide: "खरीदें",
    sellSide: "बेचें",
  },
  help: {
    title: "यह पटल कैसे चलता है",
    aT: "दो सीटें, एक सिक्का",
    aB: "व्यापारी विज्ञापन देता है। खरीदार उसे लेता है। मुद्रा ओर्विया के बाहर दी जाती है। सिक्का तब तक अवरुद्ध रहता है जब तक व्यापारी उसे न छोड़े।",
    bT: "व्यापारी अनुज्ञप्ति",
    bB: "पहचान के बाद प्रशासन व्यापारी अनुज्ञप्ति देता है। दस्तावेज़ राष्ट्रीय पहचान, पारपत्र, या देश का कर क्रमांक होता है, जैसे भारत में पैन। केवल अंतिम चार अंक रखे जाते हैं।",
    cT: "खरीदार अनुज्ञप्ति",
    cB: "किसी व्यापारी से पहली खरीद पर उसी से पहचान होती है। वे अपनी चार अंकों और चार यादृच्छिक अंकों की अनुज्ञप्ति दे सकते हैं। बाद की खरीद में पहचान नहीं। वापस लेने पर पहचान फिर चाहिए। नया अनुरोध वे जब चाहें स्वीकार कर सकते हैं।",
    dT: "शुल्क",
    dB: "प्रशासन खरीदार शुल्क और विक्रेता शुल्क अलग रखता है। हर एक प्रतिशत हो सकता है, हर सौदे पर निश्चित सिक्का हो सकता है, या दोनों एक साथ।",
    eT: "सिक्का बाहर भेजना",
    eB: "दूसरे पटल के पते पर अंतरण प्रशासन पूरा करता है। राशि सीमा से कम हो तो प्रशासन स्वचालित या मानवी चुन सकता है। सीमा पाँच सिक्कों से शुरू होती है और बदली जा सकती है।",
    fT: "पटल पर क्या रहता है",
    fB: "शेष, सौदे और अनुज्ञप्ति इसी पटल के साथ रहते हैं। यहाँ से कुछ प्रसारित नहीं होता, और पहचान में केवल अंतिम चार अंक रहते हैं।",
  },
  profile: {
    title: "खाता",
    acting: "आप इस रूप में हैं",
    switch: "भूमिका बदलें",
    seat: "इस पटल की भूमिकाएँ इसी ब्राउज़र में रहती हैं। व्यापारी अनुज्ञप्ति देता है और सिक्का छोड़ता है। प्रशासन शुल्क और अंतरण रखता है। प्रशासन स्वयं नहीं खुलता।",
    reset: "पटल आँकड़े पुनःस्थापित करें",
    resetWarn: "इससे मूल विज्ञापन, सौदे और अनुज्ञप्ति लौट आती हैं।",
    resetDo: "अभी पुनःस्थापित करें",
    done: "पटल लौट आया।",
    blocked: "रोके हुए",
    following: "अनुसरण",
    noneList: "अभी कोई नहीं।",
  },
  footer: { sim: "डीएलएम कैश लैब्स प्राइवेट लिमिटेड", rights: "ओर्विया" },
  rail: {
    upi: "यूपीआई",
    imps: "आईएमपीएस",
    bank: "बैंक हस्तांतरण",
    paytm: "पेटीएम",
    jazz: "जैज़कैश",
    easy: "ईज़ीपैसा",
    card: "भुगतान पत्र",
  },
  fiatName: { INR: "भारतीय रुपया", USD: "अमेरिकी डॉलर", PKR: "पाकिस्तानी रुपया", AED: "अमीरात दिरहम", EUR: "यूरो" },
  coinName: {
    ORB: "ऑर्बिट",
    VLT: "वॉल्ट",
    KYN: "काइन",
    AUR: "ऑरा",
    PXN: "पेक्सन",
    LUM: "ल्यूमेन",
    NRX: "नेरिक्स",
    HAL: "हेलो",
    BTC: "बिटकॉइन",
    ETH: "एथेरियम",
    USDT: "टेथर",
    BNB: "बीएनबी",
    XRP: "एक्सआरपी",
    USDC: "अमेरिकी सिक्का",
    SOL: "सोलाना",
    TRX: "ट्रॉन",
    ZEC: "ज़कैश",
    HYPE: "हाइपरलिक्विड",
  },
  country: {
    IN: "भारत",
    US: "संयुक्त राज्य",
    GB: "ब्रिटेन",
    PK: "पाकिस्तान",
    AE: "संयुक्त अरब अमीरात",
    CA: "कनाडा",
    AU: "ऑस्ट्रेलिया",
    DE: "जर्मनी",
    FR: "फ़्रांस",
    BR: "ब्राज़ील",
    NG: "नाइजीरिया",
    ZA: "दक्षिण अफ़्रीका",
    SG: "सिंगापुर",
    BD: "बांग्लादेश",
    NP: "नेपाल",
    LK: "श्रीलंका",
    CN: "चीन",
    JP: "जापान",
    ID: "इंडोनेशिया",
    PH: "फ़िलिपींस",
    KE: "केन्या",
    SA: "सऊदी अरब",
    TR: "तुर्की",
    MX: "मेक्सिको",
    ES: "स्पेन",
    IT: "इटली",
    NL: "नीदरलैंड",
    QA: "क़तर",
  },
  tax: {
    PAN: "स्थायी खाता संख्या",
    SSN: "सामाजिक सुरक्षा संख्या",
    ITIN: "व्यक्तिगत करदाता संख्या",
    UTR: "अद्वितीय करदाता संदर्भ",
    NINO: "राष्ट्रीय बीमा संख्या",
    NTN: "राष्ट्रीय कर संख्या",
    TRN: "कर पंजीकरण संख्या",
    SIN: "सामाजिक बीमा संख्या",
    TFN: "कर संचिका संख्या",
    STEUER: "कर पहचान संख्या",
    SPI: "कर संख्या",
    CF: "राजकोषीय संकेत",
    NIF: "कर पहचान संख्या",
    BSN: "नागरिक सेवा संख्या",
    CPF: "प्राकृतिक व्यक्ति पंजी",
    RFC: "संघीय करदाता पंजी",
    TIN_NG: "करदाता पहचान संख्या",
    SARS: "राजस्व सेवा संख्या",
    NRIC: "राष्ट्रीय पंजी पहचान",
    TIN_BD: "करदाता पहचान संख्या",
    PAN_NP: "स्थायी खाता संख्या",
    TIN_LK: "करदाता पहचान संख्या",
    TIN_CN: "करदाता पहचान संख्या",
    MYNO: "व्यक्तिगत संख्या",
    NPWP: "करदाता पंजी संख्या",
    TIN_PH: "करदाता पहचान संख्या",
    KRA: "राजस्व प्राधिकरण संख्या",
    TIN_SA: "करदाता पहचान संख्या",
    VKN: "कर पहचान संख्या",
    TIN_QA: "कर पत्र संख्या",
  },
  doc: { national_id: "राष्ट्रीय पहचान", passport: "पारपत्र", tax_id: "कर क्रमांक" },
  net: { mesh: "ओर्विया जाल", north: "उत्तरी मार्ग", south: "दक्षिणी मार्ग" },
  err: {
    own: "अपना विज्ञापन नहीं ले सकते।",
    license: "इस व्यापारी की सक्रिय अनुज्ञप्ति चाहिए।",
    merchant: "बेचने के लिए सक्रिय व्यापारी अनुज्ञप्ति चाहिए।",
    limits: "राशि विज्ञापन की सीमा से बाहर है।",
    available: "इस विज्ञापन में पर्याप्त सिक्का नहीं।",
    balance: "मुक्त सिक्का पर्याप्त नहीं।",
    fee: "शुल्क पूरे सौदे को खा जाएगा। राशि बढ़ाएँ या शुल्क घटाएँ।",
    address: "कम से कम ८ अक्षरों का गंतव्य लिखें।",
    amount: "मान्य राशि लिखें।",
    rails: "कम से कम एक भुगतान मार्ग चुनें।",
    price: "मान्य मूल्य लिखें।",
    inventory: "विज्ञापन में कितना सिक्का हो, लिखें।",
    range: "न्यूनतम, अधिकतम से बड़ा नहीं हो सकता।",
    name: "पूरा नाम लिखें।",
    last4: "ठीक चार अंक लिखें।",
    pending: "एक समीक्षा पहले से खुली है।",
    pass: "अनुज्ञप्ति पहले से सक्रिय है।",
    forbidden: "यह भूमिका यह नहीं कर सकती।",
    busy: "खुले सौदे अभी इस विज्ञापन पर हैं।",
    declare: "पहले चार अंकों की पुष्टि करें।",
    country: "देश चुनें।",
    tax: "कर क्रमांक का प्रकार चुनें।",
    closed: "यह सौदा पहले ही समाप्त है।",
    payment: "भुगतान मार्ग चुनें।",
    docs: "अग्र भाग, आवश्यक होने पर पृष्ठ भाग, और चेहरे की जाँच संलग्न करें।",
    symbol: "संकेत में ३ से ५ अक्षर लिखें।",
    duplicate: "यह संकेत पहले से है।",
    frozen: "यह भूमिका रुकी हुई है।",
    desk: "नए सौदों के लिए पटल बंद है।",
    coinOff: "यह सिक्का अभी इस दिशा में नहीं चल सकता।",
    minOut: "राशि इस सिक्के की न्यूनतम प्रेषण से कम है।",
    self: "प्रशासन की भूमिका नहीं रोकी जा सकती।",
    why: "अस्वीकार करने से पहले कारण चुनें।",
    blocked: "आपमें से किसी ने दूसरे को रोका है।",
    kyc: "इस विज्ञापन के लिए पहले पहचान चाहिए।",
    completion: "आपकी पूर्णता इस विज्ञापन से कम है।",
  },
} satisfies Copy;

export const ur = {
  brand: "ORVIA",
  product: "پٹل",
  demo: "ڈی ایل ایم کیش لیبز پرائیویٹ لمیٹڈ",
  tape: { live: "لائیو" },
  nav: {
    market: "منڈی",
    express: "فوری",
    orders: "سودے",
    wallet: "بٹوا",
    post: "اشتہار",
    passes: "اجازت نامے",
    payments: "ادائیگی",
    identity: "شناخت",
    admin: "انتظام",
    guide: "رہنما",
    profile: "کھاتہ",
    more: "مزید",
  },
  theme: { day: "دن", night: "رات", dark: "گہرا", label: "روپ" },
  lang: { label: "زبان", en: "انگریزی", hi: "ہندی", ur: "اردو" },
  role: { buyer: "خریدار", seller: "تاجر", admin: "انتظام", suspended: "روکی ہوئی" },
  side: { buy: "خریدیں", sell: "بیچیں" },
  mode: { percent: "فیصد", fixed: "مقرر", both: "دونوں", automatic: "خودکار", manual: "دستی" },
  common: {
    all: "سب",
    online: "موجود",
    amount: "رقم",
    price: "قیمت",
    available: "دستیاب",
    limits: "حد",
    payment: "ادائیگی",
    status: "حالت",
    cancel: "منسوخ",
    confirm: "تصدیق",
    save: "محفوظ کریں",
    close: "بند کریں",
    back: "واپس",
    submit: "جمع کریں",
    approve: "منظور",
    reject: "رد",
    revoke: "واپس لیں",
    pending: "انتظار",
    active: "فعال",
    copy: "نقل",
    copied: "نقل ہو گئی",
    none: "ابھی یہاں کچھ نہیں",
    you: "آپ",
    fee: "محصول",
    total: "کل",
    receive: "آپ پائیں گے",
    pay: "آپ دیں گے",
    details: "تفصیل",
    user: "شخص",
    note: "نوٹ",
    balance: "باقی",
    actions: "اعمال",
    view: "کھولیں",
    trades: "سودے",
    completion: "تکمیل",
    justNow: "ابھی",
    minutes: "{n} منٹ",
    hours: "{n} گھنٹے",
    days: "{n} دن",
    coin: "سکہ",
    fiat: "کرنسی",
    country: "ملک",
    name: "پورا نام",
    merchant: "تاجر",
    terms: "شرائط",
    search: "تاجر تلاش کریں",
    window: "ادائیگی کی مدت",
    locked: "روکا ہوا",
    free: "آزاد",
    count: "{n} اشتہار",
  },
  status: {
    created: "ادائیگی کا انتظار",
    paid: "ادائیگی ہوئی، سکہ چھوڑیں",
    released: "مکمل",
    cancelled: "منسوخ",
    disputed: "تنازع میں",
    pending_admin: "انتظام کا انتظار",
    auto_sent: "خود بخود بھیج دیا گیا",
    sent: "انتظام نے بھیجا",
    rejected: "رد شدہ",
    suspended: "روکی ہوئی",
    revoked: "واپس لی گئی",
    approved: "منظور شدہ",
  },
  system: {
    created: "سودا کھلا۔ پٹل کے باہر ادائیگی کریں، پھر ادائیگی نشان زد کریں۔",
    paid: "خریدار نے کرنسی کی ادائیگی نشان زد کی۔",
    released: "سکہ چھوڑ دیا گیا۔",
    cancelled: "سودا منسوخ۔ سکہ واپس۔",
    disputed: "تنازع کھلا۔ انتظام فیصلہ کر سکتا ہے۔",
  },
  market: {
    sub: "تاجروں کے ساتھ مشق کے سکے خریدیں اور بیچیں۔ کرنسی اس پٹل کے باہر جاتی ہے۔ سکہ یہیں تب ہلتا ہے جب تاجر اسے چھوڑے۔",
    amountPh: "کرنسی کی رقم",
    empty: "ان چھلنیوں سے کوئی اشتہار نہیں ملا۔",
    yourAd: "آپ کا اشتہار",
    verify: "شناخت کریں",
    waiting: "جائزے میں",
    verified: "مجاز",
    onlineOnly: "صرف موجود",
    followingOnly: "پیروی",
    float: "چلتی قیمت",
    minComp: "{n}% تکمیل چاہیے",
    extraId: "شناخت ضروری",
  },
  trade: {
    titleBuy: "سکہ خریدیں",
    titleSell: "سکہ بیچیں",
    youPay: "پٹل کے باہر آپ دیں گے",
    youReceive: "آپ پائیں گے",
    buyerFee: "خریدار کا محصول",
    sellerFee: "بیچنے والے کا محصول",
    escrowNote: "دونوں محصول سکے میں کٹتے ہیں۔ خریدار کا محصول ملنے والے سکے سے کٹتا ہے۔ بیچنے والے کا محصول بیچنے والے سے کٹتا ہے۔",
    needPass: "{name} سے پہلی خرید سے پہلے اجازت نامہ چاہیے۔ منظوری کے بعد پھر شناخت نہیں، جب تک وہ اسے واپس نہ لیں۔",
    kycTitle: "اس تاجر کے لیے شناخت",
    confirm: "سودا کھولیں",
    offDesk: "کرنسی اس پٹل پر نہیں ٹھہرتی۔",
    chatEmpty: "ابھی کوئی پیغام نہیں۔",
    chatPh: "پیغام لکھیں",
    send: "بھیجیں",
    markPaid: "میں نے ادائیگی کر دی",
    release: "سکہ چھوڑیں",
    cancel: "سودا منسوخ کریں",
    dispute: "تنازع کھولیں",
    windowLeft: "ادائیگی کی مدت",
    windowOver: "ادائیگی کی مدت گزر گئی۔ پھر بھی ادائیگی نشان زد کر سکتے ہیں۔",
    private: "یہ سودا آپ کا نہیں۔",
    missing: "سودا نہیں ملا۔",
    adminRelease: "انتظام چھوڑے",
    adminCancel: "انتظام منسوخ کرے",
    min: "کم از کم",
    max: "زیادہ سے زیادہ",
    net: "خریدار کے محصول کے بعد",
    room: "سودے کا کمرہ",
    rate: "دوسرے فریق کو ناپیں",
    rated: "آپ کا ناپ",
    block: "روکیں",
    unblock: "روک ہٹائیں",
    follow: "پیروی کریں",
    unfollow: "پیروی ہٹائیں",
    appealWhy: "وجہ",
    appeal: {
      not_released: "سکہ نہیں چھوڑا گیا",
      wrong_name: "نام میل نہیں کھاتا",
      no_reply: "کوئی جواب نہیں",
      amount: "رقم غلط ہے",
    },
  },
  ads: {
    title: "اشتہار دیں",
    sub: "صرف فعال اجازت نامے والا تاجر اشتہار دے سکتا ہے۔ بیچنے پر بٹوے کا سکہ اشتہار میں رک جاتا ہے۔",
    side: "آپ کا رخ",
    price: "فی سکہ قیمت",
    min: "کم از کم سکہ",
    max: "زیادہ سے زیادہ سکہ",
    inventory: "جتنا سکہ دینا یا مانگنا ہے",
    rails: "ادائیگی کے راستے",
    termsPh: "اختیاری شرائط",
    defaultTerms: "صرف سودے کے کمرے میں دکھایا کھاتہ بھریں۔ کرنسی نکلنے کے بعد ہی ادائیگی نشان زد کریں۔ اس کے بعد سکہ چھوڑا جاتا ہے۔",
    needLicense: "فعال تاجر اجازت نامہ چاہیے۔ شناخت مکمل کریں اور انتظام کا انتظار کریں۔",
    my: "آپ کے اشتہار",
    pause: "روکیں",
    resume: "جاری کریں",
    close: "اشتہار بند کریں",
    empty: "آپ کا کوئی اشتہار نہیں۔",
    posted: "اشتہار چل رہا ہے۔",
    saved: "اشتہار تازہ ہو گیا۔",
    busy: "پہلے اس اشتہار کے کھلے سودے بند کریں۔",
    mode: "قیمت کی قسم",
    fixed: "مقرر",
    float: "چلتی",
    margin: "حاشیہ فیصد",
    window: "ادائیگی کی مدت",
    auto: "خودکار جواب",
    autoPh: "سودا کھلتے ہی بھیجا جاتا ہے",
    needId: "شناخت ضروری",
    minComp: "کم از کم تکمیل",
    break: "وقفہ لیں",
    edit: "ترمیم",
    railsCap: "زیادہ سے زیادہ پانچ راستے",
  },
  orders: {
    title: "سودے",
    empty: "اس نشست پر ابھی کوئی سودا نہیں۔",
    missing: "سودا نہیں ملا۔",
    private: "یہ سودا دوسری نشست کا ہے۔",
    counterparty: "دوسرا فریق",
    room: "سودے کا کمرہ",
    youBuy: "آپ خرید رہے ہیں",
    youSell: "آپ بیچ رہے ہیں",
  },
  wallet: {
    title: "بٹوا",
    sub: "صرف مشق کا باقی۔ دوسرے پٹل کے پتے پر سکہ انتظام بھیجتا ہے، سوائے جب رقم حد سے کم ہو اور انتظام نے اسے خودکار رکھا ہو۔",
    free: "آزاد",
    inAds: "اشتہار میں",
    inOrders: "سودوں میں",
    pendingOut: "بھیجنے کا انتظار",
    ref: "حوالہ قیمت",
    topup: "مشق کا اضافہ",
    topupNote: "۱۰۰ مشق کے سکے جڑتے ہیں۔ باہر سے کچھ نہیں آتا۔",
    topupGo: "۱۰۰ جوڑیں",
    withdraw: "باہر بھیجیں",
    address: "منزل کا پتہ",
    addressPh: "دوسرے پٹل کا پتہ",
    network: "راستہ",
    amount: "سکے کی رقم",
    limitIs: "انتظام کی حد: {n} سکے",
    previewAuto: "یہ درخواست فوراً بھیجی ہوئی نشان زد ہو گی۔",
    previewManual: "یہ درخواست تب تک رکے گی جب تک انتظام نہ بھیجے۔",
    history: "منتقلیاں",
    empty: "ابھی کوئی منتقلی نہیں۔",
    policy: "بھیجنے کا طریقہ",
  },
  kyc: {
    title: "شناخت",
    sellerSub: "تاجر کا اجازت نامہ انتظام دیتا ہے۔ قومی شناخت، پاسپورٹ، یا اپنے ملک کا ٹیکس نمبر چنیں۔ بھارت میں یہ پین ہوتا ہے۔ صرف آخری چار ہندسے رکھے جاتے ہیں۔",
    buyerSub: "تاجر اسے ایک بار دیکھتا ہے۔ منظور ہونے پر اجازت نامہ ملتا ہے: ان کے چار ہندسے، پھر چار بے ترتیب ہندسے۔ جب تک وہ واپس نہ لیں، ان سے پھر شناخت نہیں۔",
    doc: "دستاویز",
    last4: "آخری چار ہندسے",
    last4Hint: "ٹھیک چار ہندسے۔ باقی نمبر کبھی محفوظ نہیں ہوتا۔",
    declare: "میں تصدیق کرتا ہوں کہ یہ چار ہندسے میری دستاویز سے ملتے ہیں، اور پورا نمبر محفوظ نہیں ہوتا۔",
    tax: "ٹیکس نمبر کی قسم",
    submitSeller: "انتظام سے تاجر اجازت نامہ مانگیں",
    submitBuyer: "تاجر کو بھیجیں",
    pendingAdmin: "انتظام کا انتظار۔",
    pendingSeller: "تاجر کا انتظار۔",
    approved: "منظور شدہ۔",
    rejected: "رد شدہ۔ دوبارہ بھیج سکتے ہیں۔",
    none: "ابھی کوئی درخواست نہیں۔",
    forMerchant: "{name} کے لیے",
    held: "موجودہ تاجر اجازت نامہ",
    front: "دستاویز کا اگلا رخ",
    back: "دستاویز کا پچھلا رخ",
    selfie: "چہرے کی جانچ",
    attach: "منسلک نشان زد کریں",
    attached: "منسلک",
    missing: "منسلک نہیں",
    docsNote: "یہ مشق کا پٹل صرف یہ درج کرتا ہے کہ فائل نشان زد ہوئی۔ کوئی تصویر محفوظ نہیں ہوتی۔",
    levelNone: "تصدیق شدہ نہیں",
    levelPending: "جائزے میں",
    levelMerchant: "تاجر تصدیق شدہ",
    levelRejected: "نئی جانچ چاہیے",
    why: "وجہ",
    evidence: "ثبوت",
    reasons: {
      incomplete: "دستاویزات نامکمل",
      blur: "دستاویز پڑھی نہیں گئی",
      mismatch: "نام ہندسوں سے نہیں ملتا",
      expired: "دستاویز پرانی ہے",
    },
  },
  pass: {
    title: "اجازت نامے",
    sub: "خریدار کا اجازت نامہ اس تاجر کے ساتھ تب تک مستقل ہے جب تک وہ اسے واپس نہ لے۔ واپسی کا مطلب نئی شناخت ہے۔ نئی درخواست وہ کبھی بھی منظور کر سکتے ہیں۔",
    merchantLicense: "تاجر کا اجازت نامہ",
    noneLicense: "اس نشست پر تاجر کا اجازت نامہ نہیں۔",
    code: "رمز",
    yourPasses: "آپ کے پاس اجازت نامے",
    issued: "درخواستیں جن پر آپ فیصلہ کرتے ہیں",
    emptyHeld: "ابھی کوئی اجازت نامہ نہیں۔ تاجر کے اشتہار سے شناخت کریں۔",
    emptyIssued: "ابھی کسی خریدار نے نہیں پوچھا۔",
    permanent: "فعال رہتے اس تاجر کے ساتھ مستقل۔",
    revokedNote: "واپس لے لیا گیا۔ ان سے پھر خریدنے سے پہلے نئی شناخت چاہیے۔",
    by: "تاجر",
    grant: "اجازت نامہ دیں",
    deny: "رد کریں",
    holder: "خریدار",
    suspended: "انتظام نے اجازت نامہ روک دیا۔",
  },
  admin: {
    title: "انتظامی پٹل",
    gate: "محصول، شناخت اور باہر جانے والی منتقلی کے لیے انتظامی نشست چنیں۔",
    switch: "انتظام بنیں",
    overview: "خلاصہ",
    fees: "محصول",
    withdrawals: "منتقلیاں",
    identity: "شناخت",
    coins: "سکے",
    orders: "سودے",
    users: "لوگ",
    policy: "خریدار اور بیچنے والے کا محصول الگ ہے۔ فیصد، ہر سودے پر مقرر سکہ، یا دونوں ایک ساتھ رکھ سکتے ہیں۔",
    buyerPercent: "خریدار کا فیصد",
    sellerPercent: "بیچنے والے کا فیصد",
    buyerFixed: "خریدار کا مقرر سکہ",
    sellerFixed: "بیچنے والے کا مقرر سکہ",
    under: "حد سے کم",
    over: "حد پر اور اس سے زیادہ",
    threshold: "سکے میں حد",
    save: "قاعدے محفوظ کریں",
    saved: "قاعدے محفوظ ہو گئے۔",
    queueEmpty: "قطار خالی ہے۔",
    send: "بھیجا نشان زد کریں",
    reject: "سکہ واپس کریں",
    listed: "فہرست میں",
    unlist: "چھپائیں",
    list: "دکھائیں",
    addCoin: "بے ترتیب سکہ جاری کریں",
    added: "سکہ {coin} فہرست میں ہے۔",
    newCoin: "نیا سکہ",
    suspend: "اجازت نامہ روکیں",
    resume: "اجازت نامہ بحال کریں",
    openOrders: "کھلے سودے",
    pendingKyc: "شناخت کا انتظار",
    pendingWd: "منتقلی کا انتظار",
    treasury: "جمع شدہ محصول",
    noTreasury: "ابھی محصول نہیں۔",
    merchantDecides: "خریدار کا اجازت نامہ تاجر طے کرتا ہے۔ یہ فہرست صرف نگرانی کے لیے ہے۔",
    sellerQueue: "تاجر اجازت نامے کی درخواستیں",
    people: "نشستیں",
    sendBody: "دوسرے پٹل پر جانے والا سکہ اسی قطار سے بھیجا جاتا ہے، سوائے حد سے کم رقم کے جب خودکار چنا ہو۔",
    noLicense: "اجازت نامہ نہیں",
    controls: "کنٹرول",
    coinForm: "سکہ فہرست میں رکھیں",
    symbol: "علامت",
    coinName: "نام",
    refPrice: "حوالہ قیمت",
    minOut: "کم از کم بھیجنا",
    deposits: "مشق کی جمع",
    withdrawalsOn: "باہر بھیجنا",
    on: "چالو",
    off: "بند",
    saveCoin: "سکہ محفوظ کریں",
    coinSaved: "سکہ {coin} بدل گیا۔",
    desk: "پٹل",
    deskOpen: "پٹل کھلا ہے۔ نئے اشتہار اور سودے چلیں گے۔",
    deskClosed: "پٹل بند ہے۔ نئے اشتہار یا سودے نہیں۔",
    openDesk: "پٹل کھولیں",
    closeDesk: "پٹل بند کریں",
    holdOut: "منتقلی روکیں",
    releaseOut: "منتقلی چالو کریں",
    freeze: "نشست روکیں",
    unfreeze: "نشست کھولیں",
    frozen: "نشست رک گئی۔ وہ سودا یا منتقلی نہیں کر سکتے۔",
    auditTitle: "کنٹرول کا ریکارڈ",
    auditEmpty: "ابھی کوئی کنٹرول نہیں ہوا۔",
    auditKycYes: "تاجر کی جانچ منظور · {detail}",
    auditKycNo: "تاجر کی جانچ رد · {detail}",
    auditCoin: "سکے کی تبدیلی · {detail}",
    auditSeat: "نشست کا کنٹرول · {detail}",
    auditDesk: "پٹل · {detail}",
    auditRelease: "زبردستی رہائی · {detail}",
    auditCancel: "زبردستی منسوخ · {detail}",
    auditSend: "منتقلی بھیجی نشان زد · {detail}",
    auditReturn: "منتقلی واپس · {detail}",
    seats: "نشست کے کنٹرول",
  },
  pay: {
    title: "ادائیگی کے طریقے",
    sub: "سودے کے کمرے میں دکھایا جاتا ہے تاکہ خریدار جانے کرنسی کہاں جانی ہے۔ اس مشق کے پٹل پر کوئی حقیقی وصولی کھاتہ نہیں۔",
    add: "طریقہ محفوظ کریں",
    rail: "راستہ",
    label: "نام",
    details: "منزل",
    detailsPh: "نمبر یا پتہ",
    saved: "محفوظ طریقے",
    remove: "ہٹائیں",
    empty: "کوئی طریقہ نہیں۔",
    need: "اشتہار سے پہلے ایک ادائیگی کا طریقہ محفوظ کریں۔",
  },
  express: {
    title: "فوری",
    sub: "کرنسی کی رقم یا سکے کی رقم لکھیں۔ پٹل بہترین قیمت چنتا ہے۔ اضافی شناخت والے اشتہار چھوڑے جا سکتے ہیں۔ سودا وہی کھلتا ہے۔",
    youGet: "جتنا سکہ ملے گا",
    best: "بہترین تاجر",
    none: "کوئی مجاز اشتہار نہیں ملا۔",
    go: "آگے بڑھیں",
    pay: "جتنی کرنسی دیں گے",
    unitFiat: "کرنسی کی رقم",
    unitCoin: "سکے کی رقم",
    skipId: "اضافی شناخت والے اشتہار چھوڑیں",
    fee: "محصول",
    window: "ادائیگی کی مدت",
    buySide: "خریدیں",
    sellSide: "بیچیں",
  },
  help: {
    title: "یہ پٹل کیسے چلتا ہے",
    aT: "دو نشستیں، ایک سکہ",
    aB: "تاجر اشتہار دیتا ہے۔ خریدار اسے لیتا ہے۔ کرنسی اورویا کے باہر دی جاتی ہے۔ سکہ تب تک رکا رہتا ہے جب تک تاجر اسے نہ چھوڑے۔",
    bT: "تاجر کا اجازت نامہ",
    bB: "شناخت کے بعد انتظام تاجر کا اجازت نامہ دیتا ہے۔ دستاویز قومی شناخت، پاسپورٹ، یا ملک کا ٹیکس نمبر ہوتا ہے، جیسے بھارت میں پین۔ صرف آخری چار ہندسے رکھے جاتے ہیں۔",
    cT: "خریدار کا اجازت نامہ",
    cB: "کسی تاجر سے پہلی خرید پر اسی سے شناخت ہوتی ہے۔ وہ اپنے چار ہندسوں اور چار بے ترتیب ہندسوں کا اجازت نامہ دے سکتے ہیں۔ بعد کی خرید میں شناخت نہیں۔ واپس لینے پر شناخت پھر چاہیے۔ نئی درخواست وہ جب چاہیں منظور کر سکتے ہیں۔",
    dT: "محصول",
    dB: "انتظام خریدار کا محصول اور بیچنے والے کا محصول الگ رکھتا ہے۔ ہر ایک فیصد ہو سکتا ہے، ہر سودے پر مقرر سکہ ہو سکتا ہے، یا دونوں ایک ساتھ۔",
    eT: "سکہ باہر بھیجنا",
    eB: "دوسرے پٹل کے پتے پر منتقلی انتظام پوری کرتا ہے۔ رقم حد سے کم ہو تو انتظام خودکار یا دستی چن سکتا ہے۔ حد پانچ سکوں سے شروع ہوتی ہے اور بدلی جا سکتی ہے۔",
    fT: "پٹل پر کیا رہتا ہے",
    fB: "بقایا، سودے اور اجازت نامے اسی پٹل کے ساتھ رہتے ہیں۔ یہاں سے کچھ نشر نہیں ہوتا، اور شناخت میں صرف آخری چار ہندسے رہتے ہیں۔",
  },
  profile: {
    title: "کھاتہ",
    acting: "آپ اس روپ میں ہیں",
    switch: "نشست بدلیں",
    seat: "اس پٹل کے کردار اسی براؤزر میں رہتے ہیں۔ تاجر اجازت نامہ دیتا ہے اور سکہ چھوڑتا ہے۔ انتظام محصول اور منتقلی رکھتا ہے۔ انتظام خود نہیں کھلتا۔",
    reset: "پٹل کے اعداد بحال کریں",
    resetWarn: "اس سے اصل اشتہار، سودے اور اجازت نامے واپس آ جاتے ہیں۔",
    resetDo: "ابھی بحال کریں",
    done: "پٹل واپس آ گیا۔",
    blocked: "روکے ہوئے",
    following: "پیروی",
    noneList: "ابھی کوئی نہیں۔",
  },
  footer: { sim: "ڈی ایل ایم کیش لیبز پرائیویٹ لمیٹڈ", rights: "اورویا" },
  rail: {
    upi: "یو پی آئی",
    imps: "آئی ایم پی ایس",
    bank: "بینک منتقلی",
    paytm: "پے ٹی ایم",
    jazz: "جاز کیش",
    easy: "ایزی پیسہ",
    card: "بطاقہ",
  },
  fiatName: { INR: "بھارتی روپیہ", USD: "امریکی ڈالر", PKR: "پاکستانی روپیہ", AED: "اماراتی درہم", EUR: "یورو" },
  coinName: {
    ORB: "آربٹ",
    VLT: "والٹ",
    KYN: "کائن",
    AUR: "آورا",
    PXN: "پیکسن",
    LUM: "لیومن",
    NRX: "نیرکس",
    HAL: "ہیلو",
    BTC: "بٹ کوائن",
    ETH: "ایتھیریم",
    USDT: "ٹیتھر",
    BNB: "بی این بی",
    XRP: "ایکس آر پی",
    USDC: "امریکی سکہ",
    SOL: "سولانا",
    TRX: "ٹرون",
    ZEC: "زی کیش",
    HYPE: "ہائپر لیکویڈ",
  },
  country: {
    IN: "بھارت",
    US: "ریاست ہائے متحدہ",
    GB: "برطانیہ",
    PK: "پاکستان",
    AE: "متحدہ عرب امارات",
    CA: "کینیڈا",
    AU: "آسٹریلیا",
    DE: "جرمنی",
    FR: "فرانس",
    BR: "برازیل",
    NG: "نائجیریا",
    ZA: "جنوبی افریقہ",
    SG: "سنگاپور",
    BD: "بنگلہ دیش",
    NP: "نیپال",
    LK: "سری لنکا",
    CN: "چین",
    JP: "جاپان",
    ID: "انڈونیشیا",
    PH: "فلپائن",
    KE: "کینیا",
    SA: "سعودی عرب",
    TR: "ترکی",
    MX: "میکسیکو",
    ES: "ہسپانیہ",
    IT: "اٹلی",
    NL: "نیدرلینڈز",
    QA: "قطر",
  },
  tax: {
    PAN: "مستقل کھاتہ نمبر",
    SSN: "سماجی تحفظ نمبر",
    ITIN: "انفرادی ٹیکس دہندہ نمبر",
    UTR: "منفرد ٹیکس دہندہ حوالہ",
    NINO: "قومی بیمہ نمبر",
    NTN: "قومی ٹیکس نمبر",
    TRN: "ٹیکس رجسٹریشن نمبر",
    SIN: "سماجی بیمہ نمبر",
    TFN: "ٹیکس فائل نمبر",
    STEUER: "ٹیکس شناخت نمبر",
    SPI: "ٹیکس نمبر",
    CF: "مالیاتی کوڈ",
    NIF: "ٹیکس شناخت نمبر",
    BSN: "شہری خدمت نمبر",
    CPF: "قدرتی شخص کا رجسٹر",
    RFC: "وفاقی ٹیکس دہندہ رجسٹری",
    TIN_NG: "ٹیکس دہندہ شناخت نمبر",
    SARS: "محصول خدمت نمبر",
    NRIC: "قومی رجسٹریشن شناخت",
    TIN_BD: "ٹیکس دہندہ شناخت نمبر",
    PAN_NP: "مستقل کھاتہ نمبر",
    TIN_LK: "ٹیکس دہندہ شناخت نمبر",
    TIN_CN: "ٹیکس دہندہ شناخت نمبر",
    MYNO: "انفرادی نمبر",
    NPWP: "ٹیکس دہندہ رجسٹریشن نمبر",
    TIN_PH: "ٹیکس دہندہ شناخت نمبر",
    KRA: "محصول اتھارٹی نمبر",
    TIN_SA: "ٹیکس دہندہ شناخت نمبر",
    VKN: "ٹیکس شناخت نمبر",
    TIN_QA: "ٹیکس کارت نمبر",
  },
  doc: { national_id: "قومی شناخت", passport: "گذرنامہ", tax_id: "ٹیکس نمبر" },
  net: { mesh: "اورویا جال", north: "شمالی راستہ", south: "جنوبی راستہ" },
  err: {
    own: "اپنا اشتہار نہیں لے سکتے۔",
    license: "اس تاجر کا فعال اجازت نامہ چاہیے۔",
    merchant: "بیچنے کے لیے فعال تاجر اجازت نامہ چاہیے۔",
    limits: "رقم اشتہار کی حد سے باہر ہے۔",
    available: "اس اشتہار میں کافی سکہ نہیں۔",
    balance: "آزاد سکہ کافی نہیں۔",
    fee: "محصول پورے سودے کو کھا جائے گا۔ رقم بڑھائیں یا محصول گھٹائیں۔",
    address: "کم از کم ۸ حروف کی منزل لکھیں۔",
    amount: "درست رقم لکھیں۔",
    rails: "کم از کم ایک ادائیگی کا راستہ چنیں۔",
    price: "درست قیمت لکھیں۔",
    inventory: "اشتہار میں کتنا سکہ ہو، لکھیں۔",
    range: "کم از کم، زیادہ سے زیادہ سے بڑا نہیں ہو سکتا۔",
    name: "پورا نام لکھیں۔",
    last4: "ٹھیک چار ہندسے لکھیں۔",
    pending: "ایک جائزہ پہلے سے کھلا ہے۔",
    pass: "اجازت نامہ پہلے سے فعال ہے۔",
    forbidden: "یہ نشست یہ نہیں کر سکتی۔",
    busy: "کھلے سودے ابھی اس اشتہار پر ہیں۔",
    declare: "پہلے چار ہندسوں کی تصدیق کریں۔",
    country: "ملک چنیں۔",
    tax: "ٹیکس نمبر کی قسم چنیں۔",
    closed: "یہ سودا پہلے ہی ختم ہو چکا۔",
    payment: "ادائیگی کا راستہ چنیں۔",
    docs: "اگلا رخ، ضرورت ہو تو پچھلا رخ، اور چہرے کی جانچ منسلک کریں۔",
    symbol: "علامت میں ۳ سے ۵ حروف لکھیں۔",
    duplicate: "یہ علامت پہلے سے موجود ہے۔",
    frozen: "یہ نشست رک گئی ہے۔",
    desk: "نئے سودوں کے لیے پٹل بند ہے۔",
    coinOff: "یہ سکہ اس سمت ابھی نہیں چل سکتا۔",
    minOut: "رقم اس سکے کی کم از کم منتقلی سے کم ہے۔",
    self: "انتظامی نشست نہیں روکی جا سکتی۔",
    why: "رد کرنے سے پہلے وجہ چنیں۔",
    blocked: "آپ میں سے کسی نے دوسرے کو روکا ہے۔",
    kyc: "اس اشتہار کے لیے پہلے شناخت چاہیے۔",
    completion: "آپ کی تکمیل اس اشتہار سے کم ہے۔",
  },
} satisfies Copy;

const books: Record<Lang, Copy> = { en, hi, ur };

export function tr(lang: Lang, path: string, vars?: Record<string, string | number>) {
  const parts = path.split(".");
  let node: unknown = books[lang];
  for (const part of parts) {
    if (node && typeof node === "object" && part in node) node = (node as Record<string, unknown>)[part];
    else return path;
  }
  if (typeof node !== "string") return path;
  if (!vars) return node;
  return node.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? ""));
}
