
/** Extra Market ADVANCE + Admin strings merged by i18n when present. */
export const copyExtras = {
  en: {
    market: {
      tab: { express: "Express", p2p: "P2P", block: "Block" },
      userCenter: "User Center",
      help: "Help",
      helpStub: "Help center — paper stub",
      expressStub: "Express match (pay/receive + fee rate) is not in the paper store yet",
      blockStub: "Block counterparties — use profile blocks in paper mode",
      sortBy: "Sort by",
      sortCompletion: "Completion %",
      sortPayMin: "Pay time",
      sortOrders: "Order count",
      merchantsOnly: "Merchants",
      beginnerMode: "Beginner mode",
      advancedFilters: "Filters",
      advancedStub: "Advanced filter panel (Binance funnel) — UI stub; no private scrape",
      youReceive: "You receive ~{n} {coin}",
      youPay: "You pay ~{n} {coin}",
    },
  },
  hi: {
    market: {
      tab: { express: "एक्सप्रेस", p2p: "P2P", block: "ब्लॉक" },
      userCenter: "यूज़र सेंटर",
      help: "मदद",
      helpStub: "हेल्प सेंटर — पेपर स्टब",
      expressStub: "एक्सप्रेस मैच अभी पेपर स्टोर में नहीं है",
      blockStub: "ब्लॉक सूची — प्रोफ़ाइल ब्लॉक इस्तेमाल करें",
      sortBy: "क्रम",
      sortCompletion: "पूर्णता %",
      sortPayMin: "भुगतान समय",
      sortOrders: "ऑर्डर संख्या",
      merchantsOnly: "व्यापारी",
      beginnerMode: "बिगिनर मोड",
      advancedFilters: "फ़िल्टर",
      advancedStub: "एडवांस्ड फ़िल्टर पैनल — केवल UI स्टब",
      youReceive: "आपको ~{n} {coin} मिलेंगे",
      youPay: "आप ~{n} {coin} देंगे",
    },
  },
  ur: {
    market: {
      tab: { express: "ایکسپریس", p2p: "P2P", block: "بلاک" },
      userCenter: "یوزر سینٹر",
      help: "مدد",
      helpStub: "ہیلپ سینٹر — پیپر اسٹب",
      expressStub: "ایکسپریس میچ ابھی پیپر اسٹور میں نہیں",
      blockStub: "بلاک فہرست — پروفائل بلاک استعمال کریں",
      sortBy: "ترتیب",
      sortCompletion: "تکمیل %",
      sortPayMin: "ادائیگی وقت",
      sortOrders: "آرڈر تعداد",
      merchantsOnly: "تاجر",
      beginnerMode: "بیگنر موڈ",
      advancedFilters: "فلٹرز",
      advancedStub: "ایڈوانسڈ فلٹر پینل — صرف UI اسٹب",
      youReceive: "آپ کو ~{n} {coin} ملیں گے",
      youPay: "آپ ~{n} {coin} دیں گے",
    },
  },
} as const;
