/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExpressRouteImport } from './routes/express'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PassesRouteImport } from './routes/passes'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PostRouteImport } from './routes/post'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpressRoute = ExpressRouteImport.update({
  id: '/express',
  path: '/express',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesRoute = PassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/orders': typeof OrdersRoute
  '/passes': typeof PassesRoute
  '/payments': typeof PaymentsRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/wallet': typeof WalletRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/orders': typeof OrdersRoute
  '/passes': typeof PassesRoute
  '/payments': typeof PaymentsRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/wallet': typeof WalletRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/journal': typeof JournalRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/orders': typeof OrdersRoute
  '/passes': typeof PassesRoute
  '/payments': typeof PaymentsRoute
  '/post': typeof PostRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/wallet': typeof WalletRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/buy'
    | '/contact'
    | '/desk'
    | '/express'
    | '/faq'
    | '/fees'
    | '/guide'
    | '/help'
    | '/identity'
    | '/journal'
    | '/legal'
    | '/login'
    | '/merchant'
    | '/orders'
    | '/passes'
    | '/payments'
    | '/post'
    | '/pricing'
    | '/product'
    | '/profile'
    | '/security'
    | '/sell'
    | '/services'
    | '/wallet'
    | '/journal/$slug'
    | '/order/$orderId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/buy'
    | '/contact'
    | '/desk'
    | '/express'
    | '/faq'
    | '/fees'
    | '/guide'
    | '/help'
    | '/identity'
    | '/journal'
    | '/legal'
    | '/login'
    | '/merchant'
    | '/orders'
    | '/passes'
    | '/payments'
    | '/post'
    | '/pricing'
    | '/product'
    | '/profile'
    | '/security'
    | '/sell'
    | '/services'
    | '/wallet'
    | '/journal/$slug'
    | '/order/$orderId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/buy'
    | '/contact'
    | '/desk'
    | '/express'
    | '/faq'
    | '/fees'
    | '/guide'
    | '/help'
    | '/identity'
    | '/journal'
    | '/legal'
    | '/login'
    | '/merchant'
    | '/orders'
    | '/passes'
    | '/payments'
    | '/post'
    | '/pricing'
    | '/product'
    | '/profile'
    | '/security'
    | '/sell'
    | '/services'
    | '/wallet'
    | '/journal/$slug'
    | '/order/$orderId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  DeskRoute: typeof DeskRoute
  ExpressRoute: typeof ExpressRoute
  FaqRoute: typeof FaqRoute
  FeesRoute: typeof FeesRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  IdentityRoute: typeof IdentityRoute
  JournalRoute: typeof JournalRouteWithChildren
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRoute
  OrdersRoute: typeof OrdersRoute
  PassesRoute: typeof PassesRoute
  PaymentsRoute: typeof PaymentsRoute
  PostRoute: typeof PostRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ProfileRoute: typeof ProfileRoute
  SecurityRoute: typeof SecurityRoute
  SellRoute: typeof SellRoute
  ServicesRoute: typeof ServicesRoute
  WalletRoute: typeof WalletRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/express': {
      id: '/express'
      path: '/express'
      fullPath: '/express'
      preLoaderRoute: typeof ExpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  DeskRoute: DeskRoute,
  ExpressRoute: ExpressRoute,
  FaqRoute: FaqRoute,
  FeesRoute: FeesRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  IdentityRoute: IdentityRoute,
  JournalRoute: JournalRouteWithChildren,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRoute,
  OrdersRoute: OrdersRoute,
  PassesRoute: PassesRoute,
  PaymentsRoute: PaymentsRoute,
  PostRoute: PostRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ProfileRoute: ProfileRoute,
  SecurityRoute: SecurityRoute,
  SellRoute: SellRoute,
  ServicesRoute: ServicesRoute,
  WalletRoute: WalletRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
